#! /usr/bin/env php
<?php

use CraftCli\InstallCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Craft CLI', '1.0');

$app->add(new InstallCommand(new GuzzleHttp\Client));

$app->run();
