#! /usr/bin/env php

<?php

use CraftCli\InstallCommand;
use CraftCli\UpdateCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Craft CLI', '1.0');

$app->add(new InstallCommand());

$app->run();
